---
title: "04_main"
author: "Tyler Weiglein"
date: "2/28/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r cars}
library(tidyverse)
library(lubridate)
## Main script for phenology analysis

## Load required functions
if(file.exists("01_download_phenocam.R")) source("01_download_phenocam.R")
if(file.exists("02_plot_phenocam.R"))     source("02_plot_phenocam.R")
if(file.exists("03_logistic.R"))          source("03_logistic.R")

## Download phenology data
URL <- "http://phenocam.sr.unh.edu/data/archive/uiefprairie/ROI/uiefprairie_GR_1000_1day.csv"
prairie_pheno <- download_phenocam(URL)

## Plot overall phenology data
plot_phenocam(prairie_pheno)

## Create and visualize subset of data for leaf out
spring <- as_date(c("2015-01-01","2015-06-01"))
dat <- prairie_pheno %>% 
  filter(date > spring[1], 
         date < spring[2]) %>% 
  select(date, gcc_mean, gcc_std)
  
plot_phenocam(dat)

## Fit logistic model
dat <- dat %>% 
  mutate(doy = yday(date))
par <- c(0.33,0.11,-10,0.1)
fit_pars <- fit_logistic(dat, par)
pred <- tibble(date = dat$date,
               pred = pred_logistic(fit_pars, dat$doy))

## Visualize model and data
plot_phenocam(dat, pred = pred)
```